test_that("score calculated corectly", {
  expect_equal(es_ii(data.frame(age = c(55),
               female = c(0),
               nyha = c(1),
               ccs4 = c(0),
               iddm = c(0),
               eca = c(0),
               cpd = c(0),
               nm_mob = c(0),
               redo = c(0),
               renal_dysfunc = c(86),
               active_endo = c(0),
               critical = c(0),
               lv_func= c(55),
               recent_mi = c(0),
               spap = c(20),
               urgency = c('elective'),
               proc_weight = c('single-CABG'),
               thoracic_aorta = c(0))
  )
  , data.frame(es_ii = c(0.5)))
  expect_equal(es_ii(data.frame(age = c(55, 60, 65, 70),
               female = c(0, 0, 1, 1),
               nyha = c(1, 2, 3, 4),
               ccs4 = c(0, 0, 1, 1),
               iddm = c(0, 0, 1, 1),
               eca = c(0, 0, 1, 0),
               cpd = c(0, 0, 0, 1),
               nm_mob = c(0, 0, 1, 0),
               redo = c(0, 0, 0, 1),
               renal_dysfunc = c(86,50, 35, 999),
               active_endo = c(0, 0, 1, 1),
               critical = c(0, 0, 1, 0),
               lv_func= c(55, 44, 33, 22),
               recent_mi = c(0, 0, 0, 1),
               spap = c(20, 30, 40, 50),
               urgency = c('elective',
                             'urgent',
                             'emergent',
                             'salvage'),
               proc_weight = c('single-CABG',
                                 'single-non-CABG',
                                 '2-procedures',
                                 '3-procedures'),
               thoracic_aorta = c(0, 0, 1, 1)))
    , data.frame(es_ii = c(0.50, 1.97, 72.71, 93.73)))
})
